// DO NOT EDIT. generated by webtyp.com/ormc

package mcp

import (
	"webtyp.com/model"
)

type rpcRequest struct {
	Jsonrpc string
	Id string
	Method string
	Params string
}

func (m *rpcRequest) ModelName() string { return "rpc_request" }

func (m *rpcRequest) Schema() []model.Field { return rpcRequestModel.Fields }

func (m *rpcRequest) Pointers() []any { return []any{&m.Jsonrpc, &m.Id, &m.Method, &m.Params} }

func (m *rpcRequest) IsNil() bool { return m == nil }

func (m *rpcRequest) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.Jsonrpc)
	w.Raw("id", m.Id)
	w.String("method", m.Method)
	w.Raw("params", m.Params)
}

func (m *rpcRequest) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.Jsonrpc = v }
	if v, ok := r.Raw("id"); ok { m.Id = v }
	if v, ok := r.String("method"); ok { m.Method = v }
	if v, ok := r.Raw("params"); ok { m.Params = v }
}

type rpcRequestList []*rpcRequest

func (s *rpcRequestList) Len() int             { return len(*s) }
func (s *rpcRequestList) At(i int) model.Fielder { return (*s)[i] }
func (s *rpcRequestList) Append() model.Fielder  { v := &rpcRequest{}; *s = append(*s, v); return v }
func (s *rpcRequestList) IsNil() bool          { return s == nil }
func (s *rpcRequestList) EncodeFields(_ model.FieldWriter) {}
func (s *rpcRequestList) DecodeFields(_ model.FieldReader) {}

func (m *rpcRequest) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type rpcResponse struct {
	Jsonrpc string
	Id string
	Result string
	Error string
}

func (m *rpcResponse) ModelName() string { return "rpc_response" }

func (m *rpcResponse) Schema() []model.Field { return rpcResponseModel.Fields }

func (m *rpcResponse) Pointers() []any { return []any{&m.Jsonrpc, &m.Id, &m.Result, &m.Error} }

func (m *rpcResponse) IsNil() bool { return m == nil }

func (m *rpcResponse) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.Jsonrpc)
	w.Raw("id", m.Id)
	if len(m.Result) != 0 { w.Raw("result", m.Result) }
	if len(m.Error) != 0 { w.Raw("error", m.Error) }
}

func (m *rpcResponse) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.Jsonrpc = v }
	if v, ok := r.Raw("id"); ok { m.Id = v }
	if v, ok := r.Raw("result"); ok { m.Result = v }
	if v, ok := r.Raw("error"); ok { m.Error = v }
}

type rpcResponseList []*rpcResponse

func (s *rpcResponseList) Len() int             { return len(*s) }
func (s *rpcResponseList) At(i int) model.Fielder { return (*s)[i] }
func (s *rpcResponseList) Append() model.Fielder  { v := &rpcResponse{}; *s = append(*s, v); return v }
func (s *rpcResponseList) IsNil() bool          { return s == nil }
func (s *rpcResponseList) EncodeFields(_ model.FieldWriter) {}
func (s *rpcResponseList) DecodeFields(_ model.FieldReader) {}

func (m *rpcResponse) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type jsonRPCError struct {
	Code int64
	Message string
	Data string
}

func (m *jsonRPCError) ModelName() string { return "json_rpcerror" }

func (m *jsonRPCError) Schema() []model.Field { return jsonRPCErrorModel.Fields }

func (m *jsonRPCError) Pointers() []any { return []any{&m.Code, &m.Message, &m.Data} }

func (m *jsonRPCError) IsNil() bool { return m == nil }

func (m *jsonRPCError) EncodeFields(w model.FieldWriter) {
	w.Int("code", m.Code)
	w.String("message", m.Message)
	if m.Data != "" { w.String("data", m.Data) }
}

func (m *jsonRPCError) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("code"); ok { m.Code = v }
	if v, ok := r.String("message"); ok { m.Message = v }
	if v, ok := r.String("data"); ok { m.Data = v }
}

type jsonRPCErrorList []*jsonRPCError

func (s *jsonRPCErrorList) Len() int             { return len(*s) }
func (s *jsonRPCErrorList) At(i int) model.Fielder { return (*s)[i] }
func (s *jsonRPCErrorList) Append() model.Fielder  { v := &jsonRPCError{}; *s = append(*s, v); return v }
func (s *jsonRPCErrorList) IsNil() bool          { return s == nil }
func (s *jsonRPCErrorList) EncodeFields(_ model.FieldWriter) {}
func (s *jsonRPCErrorList) DecodeFields(_ model.FieldReader) {}

func (m *jsonRPCError) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type initializeParams struct {
	ProtocolVersion string
	ClientInfo implementationInfo
}

func (m *initializeParams) ModelName() string { return "initialize_params" }

func (m *initializeParams) Schema() []model.Field { return initializeParamsModel.Fields }

func (m *initializeParams) Pointers() []any { return []any{&m.ProtocolVersion, &m.ClientInfo} }

func (m *initializeParams) IsNil() bool { return m == nil }

func (m *initializeParams) EncodeFields(w model.FieldWriter) {
	w.String("protocolVersion", m.ProtocolVersion)
	w.Object("clientInfo", &m.ClientInfo)
}

func (m *initializeParams) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("protocolVersion"); ok { m.ProtocolVersion = v }
	r.Object("clientInfo", &m.ClientInfo)
}

type initializeParamsList []*initializeParams

func (s *initializeParamsList) Len() int             { return len(*s) }
func (s *initializeParamsList) At(i int) model.Fielder { return (*s)[i] }
func (s *initializeParamsList) Append() model.Fielder  { v := &initializeParams{}; *s = append(*s, v); return v }
func (s *initializeParamsList) IsNil() bool          { return s == nil }
func (s *initializeParamsList) EncodeFields(_ model.FieldWriter) {}
func (s *initializeParamsList) DecodeFields(_ model.FieldReader) {}

func (m *initializeParams) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type implementationInfo struct {
	Name string
	Version string
}

func (m *implementationInfo) ModelName() string { return "implementation_info" }

func (m *implementationInfo) Schema() []model.Field { return implementationInfoModel.Fields }

func (m *implementationInfo) Pointers() []any { return []any{&m.Name, &m.Version} }

func (m *implementationInfo) IsNil() bool { return m == nil }

func (m *implementationInfo) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	w.String("version", m.Version)
}

func (m *implementationInfo) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("version"); ok { m.Version = v }
}

type implementationInfoList []*implementationInfo

func (s *implementationInfoList) Len() int             { return len(*s) }
func (s *implementationInfoList) At(i int) model.Fielder { return (*s)[i] }
func (s *implementationInfoList) Append() model.Fielder  { v := &implementationInfo{}; *s = append(*s, v); return v }
func (s *implementationInfoList) IsNil() bool          { return s == nil }
func (s *implementationInfoList) EncodeFields(_ model.FieldWriter) {}
func (s *implementationInfoList) DecodeFields(_ model.FieldReader) {}

func (m *implementationInfo) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type initializeResult struct {
	ProtocolVersion string
	ServerInfo implementationInfo
	Capabilities string
}

func (m *initializeResult) ModelName() string { return "initialize_result" }

func (m *initializeResult) Schema() []model.Field { return initializeResultModel.Fields }

func (m *initializeResult) Pointers() []any { return []any{&m.ProtocolVersion, &m.ServerInfo, &m.Capabilities} }

func (m *initializeResult) IsNil() bool { return m == nil }

func (m *initializeResult) EncodeFields(w model.FieldWriter) {
	w.String("protocolVersion", m.ProtocolVersion)
	w.Object("serverInfo", &m.ServerInfo)
	if len(m.Capabilities) != 0 { w.Raw("capabilities", m.Capabilities) }
}

func (m *initializeResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("protocolVersion"); ok { m.ProtocolVersion = v }
	r.Object("serverInfo", &m.ServerInfo)
	if v, ok := r.Raw("capabilities"); ok { m.Capabilities = v }
}

type initializeResultList []*initializeResult

func (s *initializeResultList) Len() int             { return len(*s) }
func (s *initializeResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *initializeResultList) Append() model.Fielder  { v := &initializeResult{}; *s = append(*s, v); return v }
func (s *initializeResultList) IsNil() bool          { return s == nil }
func (s *initializeResultList) EncodeFields(_ model.FieldWriter) {}
func (s *initializeResultList) DecodeFields(_ model.FieldReader) {}

func (m *initializeResult) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type CallToolParams struct {
	Name string
	Arguments string
}

func (m *CallToolParams) ModelName() string { return "call_tool_params" }

func (m *CallToolParams) Schema() []model.Field { return CallToolParamsModel.Fields }

func (m *CallToolParams) Pointers() []any { return []any{&m.Name, &m.Arguments} }

func (m *CallToolParams) IsNil() bool { return m == nil }

func (m *CallToolParams) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	w.Raw("arguments", m.Arguments)
}

func (m *CallToolParams) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.Raw("arguments"); ok { m.Arguments = v }
}

type CallToolParamsList []*CallToolParams

func (s *CallToolParamsList) Len() int             { return len(*s) }
func (s *CallToolParamsList) At(i int) model.Fielder { return (*s)[i] }
func (s *CallToolParamsList) Append() model.Fielder  { v := &CallToolParams{}; *s = append(*s, v); return v }
func (s *CallToolParamsList) IsNil() bool          { return s == nil }
func (s *CallToolParamsList) EncodeFields(_ model.FieldWriter) {}
func (s *CallToolParamsList) DecodeFields(_ model.FieldReader) {}

func (m *CallToolParams) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type Result struct {
	IsError bool
	Content string
}

func (m *Result) ModelName() string { return "result" }

func (m *Result) Schema() []model.Field { return ResultModel.Fields }

func (m *Result) Pointers() []any { return []any{&m.IsError, &m.Content} }

func (m *Result) IsNil() bool { return m == nil }

func (m *Result) EncodeFields(w model.FieldWriter) {
	if m.IsError { w.Bool("isError", m.IsError) }
	if len(m.Content) != 0 { w.Raw("content", m.Content) }
}

func (m *Result) DecodeFields(r model.FieldReader) {
	if v, ok := r.Bool("isError"); ok { m.IsError = v }
	if v, ok := r.Raw("content"); ok { m.Content = v }
}

type ResultList []*Result

func (s *ResultList) Len() int             { return len(*s) }
func (s *ResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *ResultList) Append() model.Fielder  { v := &Result{}; *s = append(*s, v); return v }
func (s *ResultList) IsNil() bool          { return s == nil }
func (s *ResultList) EncodeFields(_ model.FieldWriter) {}
func (s *ResultList) DecodeFields(_ model.FieldReader) {}

func (m *Result) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type TextContent struct {
	Type string
	Text string
}

func (m *TextContent) ModelName() string { return "text_content" }

func (m *TextContent) Schema() []model.Field { return TextContentModel.Fields }

func (m *TextContent) Pointers() []any { return []any{&m.Type, &m.Text} }

func (m *TextContent) IsNil() bool { return m == nil }

func (m *TextContent) EncodeFields(w model.FieldWriter) {
	w.String("type", m.Type)
	w.String("text", m.Text)
}

func (m *TextContent) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("type"); ok { m.Type = v }
	if v, ok := r.String("text"); ok { m.Text = v }
}

type TextContentList []*TextContent

func (s *TextContentList) Len() int             { return len(*s) }
func (s *TextContentList) At(i int) model.Fielder { return (*s)[i] }
func (s *TextContentList) Append() model.Fielder  { v := &TextContent{}; *s = append(*s, v); return v }
func (s *TextContentList) IsNil() bool          { return s == nil }
func (s *TextContentList) EncodeFields(_ model.FieldWriter) {}
func (s *TextContentList) DecodeFields(_ model.FieldReader) {}

func (m *TextContent) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ImageContent struct {
	Type string
	Data string
	MimeType string
}

func (m *ImageContent) ModelName() string { return "image_content" }

func (m *ImageContent) Schema() []model.Field { return ImageContentModel.Fields }

func (m *ImageContent) Pointers() []any { return []any{&m.Type, &m.Data, &m.MimeType} }

func (m *ImageContent) IsNil() bool { return m == nil }

func (m *ImageContent) EncodeFields(w model.FieldWriter) {
	w.String("type", m.Type)
	w.String("data", m.Data)
	w.String("mimeType", m.MimeType)
}

func (m *ImageContent) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("type"); ok { m.Type = v }
	if v, ok := r.String("data"); ok { m.Data = v }
	if v, ok := r.String("mimeType"); ok { m.MimeType = v }
}

type ImageContentList []*ImageContent

func (s *ImageContentList) Len() int             { return len(*s) }
func (s *ImageContentList) At(i int) model.Fielder { return (*s)[i] }
func (s *ImageContentList) Append() model.Fielder  { v := &ImageContent{}; *s = append(*s, v); return v }
func (s *ImageContentList) IsNil() bool          { return s == nil }
func (s *ImageContentList) EncodeFields(_ model.FieldWriter) {}
func (s *ImageContentList) DecodeFields(_ model.FieldReader) {}

func (m *ImageContent) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type toolEntry struct {
	Name string
	Description string
	InputSchema string
}

func (m *toolEntry) ModelName() string { return "tool_entry" }

func (m *toolEntry) Schema() []model.Field { return toolEntryModel.Fields }

func (m *toolEntry) Pointers() []any { return []any{&m.Name, &m.Description, &m.InputSchema} }

func (m *toolEntry) IsNil() bool { return m == nil }

func (m *toolEntry) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	if m.Description != "" { w.String("description", m.Description) }
	w.Raw("inputSchema", m.InputSchema)
}

func (m *toolEntry) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("description"); ok { m.Description = v }
	if v, ok := r.Raw("inputSchema"); ok { m.InputSchema = v }
}

type toolEntryList []*toolEntry

func (s *toolEntryList) Len() int             { return len(*s) }
func (s *toolEntryList) At(i int) model.Fielder { return (*s)[i] }
func (s *toolEntryList) Append() model.Fielder  { v := &toolEntry{}; *s = append(*s, v); return v }
func (s *toolEntryList) IsNil() bool          { return s == nil }
func (s *toolEntryList) EncodeFields(_ model.FieldWriter) {}
func (s *toolEntryList) DecodeFields(_ model.FieldReader) {}

func (m *toolEntry) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type listToolsResult struct {
	Tools string
	NextCursor string
}

func (m *listToolsResult) ModelName() string { return "list_tools_result" }

func (m *listToolsResult) Schema() []model.Field { return listToolsResultModel.Fields }

func (m *listToolsResult) Pointers() []any { return []any{&m.Tools, &m.NextCursor} }

func (m *listToolsResult) IsNil() bool { return m == nil }

func (m *listToolsResult) EncodeFields(w model.FieldWriter) {
	w.Raw("tools", m.Tools)
	if m.NextCursor != "" { w.String("nextCursor", m.NextCursor) }
}

func (m *listToolsResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.Raw("tools"); ok { m.Tools = v }
	if v, ok := r.String("nextCursor"); ok { m.NextCursor = v }
}

type listToolsResultList []*listToolsResult

func (s *listToolsResultList) Len() int             { return len(*s) }
func (s *listToolsResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *listToolsResultList) Append() model.Fielder  { v := &listToolsResult{}; *s = append(*s, v); return v }
func (s *listToolsResultList) IsNil() bool          { return s == nil }
func (s *listToolsResultList) EncodeFields(_ model.FieldWriter) {}
func (s *listToolsResultList) DecodeFields(_ model.FieldReader) {}

func (m *listToolsResult) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type errorResponse struct {
	Jsonrpc string
	Id string
	Error jsonRPCError
}

func (m *errorResponse) ModelName() string { return "error_response" }

func (m *errorResponse) Schema() []model.Field { return errorResponseModel.Fields }

func (m *errorResponse) Pointers() []any { return []any{&m.Jsonrpc, &m.Id, &m.Error} }

func (m *errorResponse) IsNil() bool { return m == nil }

func (m *errorResponse) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.Jsonrpc)
	w.Raw("id", m.Id)
	w.Object("error", &m.Error)
}

func (m *errorResponse) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.Jsonrpc = v }
	if v, ok := r.Raw("id"); ok { m.Id = v }
	r.Object("error", &m.Error)
}

type errorResponseList []*errorResponse

func (s *errorResponseList) Len() int             { return len(*s) }
func (s *errorResponseList) At(i int) model.Fielder { return (*s)[i] }
func (s *errorResponseList) Append() model.Fielder  { v := &errorResponse{}; *s = append(*s, v); return v }
func (s *errorResponseList) IsNil() bool          { return s == nil }
func (s *errorResponseList) EncodeFields(_ model.FieldWriter) {}
func (s *errorResponseList) DecodeFields(_ model.FieldReader) {}

func (m *errorResponse) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type Meta struct {
	ProgressToken string
}

func (m *Meta) ModelName() string { return "meta" }

func (m *Meta) Schema() []model.Field { return MetaModel.Fields }

func (m *Meta) Pointers() []any { return []any{&m.ProgressToken} }

func (m *Meta) IsNil() bool { return m == nil }

func (m *Meta) EncodeFields(w model.FieldWriter) {
	if m.ProgressToken != "" { w.String("progressToken", m.ProgressToken) }
}

func (m *Meta) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("progressToken"); ok { m.ProgressToken = v }
}

type MetaList []*Meta

func (s *MetaList) Len() int             { return len(*s) }
func (s *MetaList) At(i int) model.Fielder { return (*s)[i] }
func (s *MetaList) Append() model.Fielder  { v := &Meta{}; *s = append(*s, v); return v }
func (s *MetaList) IsNil() bool          { return s == nil }
func (s *MetaList) EncodeFields(_ model.FieldWriter) {}
func (s *MetaList) DecodeFields(_ model.FieldReader) {}

func (m *Meta) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type NotificationParams struct {
	Meta string
}

func (m *NotificationParams) ModelName() string { return "notification_params" }

func (m *NotificationParams) Schema() []model.Field { return NotificationParamsModel.Fields }

func (m *NotificationParams) Pointers() []any { return []any{&m.Meta} }

func (m *NotificationParams) IsNil() bool { return m == nil }

func (m *NotificationParams) EncodeFields(w model.FieldWriter) {
	if m.Meta != "" { w.String("meta", m.Meta) }
}

func (m *NotificationParams) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("meta"); ok { m.Meta = v }
}

type NotificationParamsList []*NotificationParams

func (s *NotificationParamsList) Len() int             { return len(*s) }
func (s *NotificationParamsList) At(i int) model.Fielder { return (*s)[i] }
func (s *NotificationParamsList) Append() model.Fielder  { v := &NotificationParams{}; *s = append(*s, v); return v }
func (s *NotificationParamsList) IsNil() bool          { return s == nil }
func (s *NotificationParamsList) EncodeFields(_ model.FieldWriter) {}
func (s *NotificationParamsList) DecodeFields(_ model.FieldReader) {}

func (m *NotificationParams) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type EmptyResult struct {
	Result string
}

func (m *EmptyResult) ModelName() string { return "empty_result" }

func (m *EmptyResult) Schema() []model.Field { return EmptyResultModel.Fields }

func (m *EmptyResult) Pointers() []any { return []any{&m.Result} }

func (m *EmptyResult) IsNil() bool { return m == nil }

func (m *EmptyResult) EncodeFields(w model.FieldWriter) {
	if m.Result != "" { w.String("result", m.Result) }
}

func (m *EmptyResult) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("result"); ok { m.Result = v }
}

type EmptyResultList []*EmptyResult

func (s *EmptyResultList) Len() int             { return len(*s) }
func (s *EmptyResultList) At(i int) model.Fielder { return (*s)[i] }
func (s *EmptyResultList) Append() model.Fielder  { v := &EmptyResult{}; *s = append(*s, v); return v }
func (s *EmptyResultList) IsNil() bool          { return s == nil }
func (s *EmptyResultList) EncodeFields(_ model.FieldWriter) {}
func (s *EmptyResultList) DecodeFields(_ model.FieldReader) {}

func (m *EmptyResult) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type JSONRPCRequest struct {
	Jsonrpc string
	Id string
	Method string
	Params string
}

func (m *JSONRPCRequest) ModelName() string { return "jsonrpcrequest" }

func (m *JSONRPCRequest) Schema() []model.Field { return JSONRPCRequestModel.Fields }

func (m *JSONRPCRequest) Pointers() []any { return []any{&m.Jsonrpc, &m.Id, &m.Method, &m.Params} }

func (m *JSONRPCRequest) IsNil() bool { return m == nil }

func (m *JSONRPCRequest) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.Jsonrpc)
	w.Raw("id", m.Id)
	w.String("method", m.Method)
	if len(m.Params) != 0 { w.Raw("params", m.Params) }
}

func (m *JSONRPCRequest) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.Jsonrpc = v }
	if v, ok := r.Raw("id"); ok { m.Id = v }
	if v, ok := r.String("method"); ok { m.Method = v }
	if v, ok := r.Raw("params"); ok { m.Params = v }
}

type JSONRPCRequestList []*JSONRPCRequest

func (s *JSONRPCRequestList) Len() int             { return len(*s) }
func (s *JSONRPCRequestList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCRequestList) Append() model.Fielder  { v := &JSONRPCRequest{}; *s = append(*s, v); return v }
func (s *JSONRPCRequestList) IsNil() bool          { return s == nil }
func (s *JSONRPCRequestList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCRequestList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCRequest) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type JSONRPCNotification struct {
	Jsonrpc string
	Method string
	Params string
}

func (m *JSONRPCNotification) ModelName() string { return "jsonrpcnotification" }

func (m *JSONRPCNotification) Schema() []model.Field { return JSONRPCNotificationModel.Fields }

func (m *JSONRPCNotification) Pointers() []any { return []any{&m.Jsonrpc, &m.Method, &m.Params} }

func (m *JSONRPCNotification) IsNil() bool { return m == nil }

func (m *JSONRPCNotification) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.Jsonrpc)
	w.String("method", m.Method)
	if len(m.Params) != 0 { w.Raw("params", m.Params) }
}

func (m *JSONRPCNotification) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.Jsonrpc = v }
	if v, ok := r.String("method"); ok { m.Method = v }
	if v, ok := r.Raw("params"); ok { m.Params = v }
}

type JSONRPCNotificationList []*JSONRPCNotification

func (s *JSONRPCNotificationList) Len() int             { return len(*s) }
func (s *JSONRPCNotificationList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCNotificationList) Append() model.Fielder  { v := &JSONRPCNotification{}; *s = append(*s, v); return v }
func (s *JSONRPCNotificationList) IsNil() bool          { return s == nil }
func (s *JSONRPCNotificationList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCNotificationList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCNotification) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type JSONRPCResponseStruct struct {
	Jsonrpc string
	Id string
	Result string
	Error string
}

func (m *JSONRPCResponseStruct) ModelName() string { return "jsonrpcresponse_struct" }

func (m *JSONRPCResponseStruct) Schema() []model.Field { return JSONRPCResponseStructModel.Fields }

func (m *JSONRPCResponseStruct) Pointers() []any { return []any{&m.Jsonrpc, &m.Id, &m.Result, &m.Error} }

func (m *JSONRPCResponseStruct) IsNil() bool { return m == nil }

func (m *JSONRPCResponseStruct) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.Jsonrpc)
	w.Raw("id", m.Id)
	if len(m.Result) != 0 { w.Raw("result", m.Result) }
	if len(m.Error) != 0 { w.Raw("error", m.Error) }
}

func (m *JSONRPCResponseStruct) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.Jsonrpc = v }
	if v, ok := r.Raw("id"); ok { m.Id = v }
	if v, ok := r.Raw("result"); ok { m.Result = v }
	if v, ok := r.Raw("error"); ok { m.Error = v }
}

type JSONRPCResponseStructList []*JSONRPCResponseStruct

func (s *JSONRPCResponseStructList) Len() int             { return len(*s) }
func (s *JSONRPCResponseStructList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCResponseStructList) Append() model.Fielder  { v := &JSONRPCResponseStruct{}; *s = append(*s, v); return v }
func (s *JSONRPCResponseStructList) IsNil() bool          { return s == nil }
func (s *JSONRPCResponseStructList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCResponseStructList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCResponseStruct) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type JSONRPCError struct {
	Jsonrpc string
	Id string
	Error string
}

func (m *JSONRPCError) ModelName() string { return "jsonrpcerror" }

func (m *JSONRPCError) Schema() []model.Field { return JSONRPCErrorModel.Fields }

func (m *JSONRPCError) Pointers() []any { return []any{&m.Jsonrpc, &m.Id, &m.Error} }

func (m *JSONRPCError) IsNil() bool { return m == nil }

func (m *JSONRPCError) EncodeFields(w model.FieldWriter) {
	w.String("jsonrpc", m.Jsonrpc)
	w.Raw("id", m.Id)
	w.Raw("error", m.Error)
}

func (m *JSONRPCError) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("jsonrpc"); ok { m.Jsonrpc = v }
	if v, ok := r.Raw("id"); ok { m.Id = v }
	if v, ok := r.Raw("error"); ok { m.Error = v }
}

type JSONRPCErrorList []*JSONRPCError

func (s *JSONRPCErrorList) Len() int             { return len(*s) }
func (s *JSONRPCErrorList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCErrorList) Append() model.Fielder  { v := &JSONRPCError{}; *s = append(*s, v); return v }
func (s *JSONRPCErrorList) IsNil() bool          { return s == nil }
func (s *JSONRPCErrorList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCErrorList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCError) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type JSONRPCErrorDetails struct {
	Code int64
	Message string
	Data string
}

func (m *JSONRPCErrorDetails) ModelName() string { return "jsonrpcerror_details" }

func (m *JSONRPCErrorDetails) Schema() []model.Field { return JSONRPCErrorDetailsModel.Fields }

func (m *JSONRPCErrorDetails) Pointers() []any { return []any{&m.Code, &m.Message, &m.Data} }

func (m *JSONRPCErrorDetails) IsNil() bool { return m == nil }

func (m *JSONRPCErrorDetails) EncodeFields(w model.FieldWriter) {
	w.Int("code", m.Code)
	w.String("message", m.Message)
	if m.Data != "" { w.String("data", m.Data) }
}

func (m *JSONRPCErrorDetails) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("code"); ok { m.Code = v }
	if v, ok := r.String("message"); ok { m.Message = v }
	if v, ok := r.String("data"); ok { m.Data = v }
}

type JSONRPCErrorDetailsList []*JSONRPCErrorDetails

func (s *JSONRPCErrorDetailsList) Len() int             { return len(*s) }
func (s *JSONRPCErrorDetailsList) At(i int) model.Fielder { return (*s)[i] }
func (s *JSONRPCErrorDetailsList) Append() model.Fielder  { v := &JSONRPCErrorDetails{}; *s = append(*s, v); return v }
func (s *JSONRPCErrorDetailsList) IsNil() bool          { return s == nil }
func (s *JSONRPCErrorDetailsList) EncodeFields(_ model.FieldWriter) {}
func (s *JSONRPCErrorDetailsList) DecodeFields(_ model.FieldReader) {}

func (m *JSONRPCErrorDetails) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

